language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install
script:
  - npm test
after_success:
  - npm run report-coverage
deploy:
  skip_cleanup: true
  provider: npm
  email: "ivansanzcarasa@gmail.com"
  api_key: "NPM_TOKEN"
  on:
    branch: master
